"""Create saved_queries table

Revision ID: db18d869cfda
Revises: 
Create Date: 2024-06-06 17:53:00.213219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db18d869cfda'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('saved_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('conditions', sa.Text(), nullable=False),
    sa.Column('search_type', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('userlog')
    op.drop_table('QueryMaster')
    op.drop_table('QueryDetailMaster')
    op.drop_table('Sheet1$')
    with op.batch_alter_table('EximExport', schema=None) as batch_op:
        batch_op.alter_column('SB_NO',
               existing_type=sa.NVARCHAR(length=25, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('HS_CODE',
               existing_type=sa.NVARCHAR(length=30, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('PRODUCT',
               existing_type=sa.NVARCHAR(length=300, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('EXPORTER',
               existing_type=sa.NVARCHAR(length=250, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('CONSIGNEE',
               existing_type=sa.VARCHAR(length=300, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('QTY',
               existing_type=sa.DECIMAL(precision=18, scale=0),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('UNIT',
               existing_type=sa.VARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('RATE_IN_FC',
               existing_type=sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('CURRENCY',
               existing_type=sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('COUNTRY',
               existing_type=sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('LOAD_PORT',
               existing_type=sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('DESTI_PORT',
               existing_type=sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('EximImport', schema=None) as batch_op:
        batch_op.alter_column('BE_NO',
               existing_type=sa.VARCHAR(length=30, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('HS_CODE',
               existing_type=sa.VARCHAR(length=30, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('PRODUCT',
               existing_type=sa.VARCHAR(length=300, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('IMPORTER',
               existing_type=sa.VARCHAR(length=200, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('SUPPLIER',
               existing_type=sa.VARCHAR(length=200, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('QTY',
               existing_type=sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('UNIT',
               existing_type=sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('RATE_IN_FC',
               existing_type=sa.VARCHAR(length=30, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('CURRENCY',
               existing_type=sa.VARCHAR(length=25, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('COUNTRY',
               existing_type=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('LOAD_PORT',
               existing_type=sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('DESTI_PORT',
               existing_type=sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('EximImport', schema=None) as batch_op:
        batch_op.alter_column('DESTI_PORT',
               existing_type=sa.String(),
               type_=sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('LOAD_PORT',
               existing_type=sa.String(),
               type_=sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('COUNTRY',
               existing_type=sa.String(),
               type_=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('CURRENCY',
               existing_type=sa.String(),
               type_=sa.VARCHAR(length=25, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('RATE_IN_FC',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=30, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('UNIT',
               existing_type=sa.String(),
               type_=sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('QTY',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('SUPPLIER',
               existing_type=sa.String(),
               type_=sa.VARCHAR(length=200, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('IMPORTER',
               existing_type=sa.String(),
               type_=sa.VARCHAR(length=200, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('PRODUCT',
               existing_type=sa.String(),
               type_=sa.VARCHAR(length=300, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('HS_CODE',
               existing_type=sa.String(),
               type_=sa.VARCHAR(length=30, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('BE_NO',
               existing_type=sa.String(),
               type_=sa.VARCHAR(length=30, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)

    with op.batch_alter_table('EximExport', schema=None) as batch_op:
        batch_op.alter_column('DESTI_PORT',
               existing_type=sa.String(),
               type_=sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('LOAD_PORT',
               existing_type=sa.String(),
               type_=sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('COUNTRY',
               existing_type=sa.String(),
               type_=sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('CURRENCY',
               existing_type=sa.String(),
               type_=sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('RATE_IN_FC',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('UNIT',
               existing_type=sa.String(),
               type_=sa.VARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('QTY',
               existing_type=sa.Float(),
               type_=sa.DECIMAL(precision=18, scale=0),
               existing_nullable=True)
        batch_op.alter_column('CONSIGNEE',
               existing_type=sa.String(),
               type_=sa.VARCHAR(length=300, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('EXPORTER',
               existing_type=sa.String(),
               type_=sa.NVARCHAR(length=250, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('PRODUCT',
               existing_type=sa.String(),
               type_=sa.NVARCHAR(length=300, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('HS_CODE',
               existing_type=sa.String(),
               type_=sa.NVARCHAR(length=30, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('SB_NO',
               existing_type=sa.String(),
               type_=sa.NVARCHAR(length=25, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)

    op.create_table('Sheet1$',
    sa.Column('BE_NO', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('BE_DATE', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.Column('HS_CODE', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('PRODUCT', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('IMPORTER', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('SUPPLIER', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('QTY', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('UNIT', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('RATE_IN_FC', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('CURRENCY', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('COUNTRY', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('LOAD_PORT', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('DESTI_PORT', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True)
    )
    op.create_table('QueryDetailMaster',
    sa.Column('qdid', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('qid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fieldname', sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('fldcond', sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('fldvalue', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('fldcase', sa.VARCHAR(length=3, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('fldoper', sa.VARCHAR(length=5, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('qdid', name='PK_QueryMaster')
    )
    op.create_table('QueryMaster',
    sa.Column('qid', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('QueryName', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('QType', sa.VARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('qid', name='PK_EximMaster')
    )
    op.create_table('userlog',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('word', sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PK_userlog')
    )
    op.drop_table('saved_queries')
    op.drop_table('users')
    # ### end Alembic commands ###
